version: '3.8'

services:
  server:
    container_name: pottysenseserver
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3005:3000"
    volumes:
      - ./sqlite.db:/app/sqlite.db  # Mount SQLite file into server container
    env_file:
      - .env
    networks:
      - psnetwork

  telebot:
    container_name: pottysensetelebot
    build: 
      context: .
      dockerfile: ./telebot/Dockerfile
    volumes:
      - ./sqlite.db:/app/sqlite.db  # Mount SQLite file into telebot container
    env_file:
      - .env
    networks:
      - psnetwork

  redis:
    container_name: pottysenseredis
    image: redis
    networks:
      - psnetwork

networks:
  psnetwork:
    driver: bridge
